// <auto-generated />
using DivingLogs.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Diving_Log.Migrations
{
    [DbContext(typeof(DivingLogContext))]
    [Migration("20201031005350_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DivingLogs.Models.DivingLog", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("date_log")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("divers_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("diving_permit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("observations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("surface_current")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wave_height")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wind_direction")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Divings");
                });
#pragma warning restore 612, 618
        }
    }
}
